name: Generate Datas

on:
  schedule:
    # Chạy mỗi 12 giờ
    - cron: "0 */12 * * *"
  # Cho phép chạy thủ công
  workflow_dispatch:
  # Chạy khi có commit vào nhánh main (hoặc master)
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Generate snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: Redamancy2107
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the content of <build_dir> to a branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
